version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: restlydb
      POSTGRES_USER: restly
      POSTGRES_PASSWORD: restlypassword
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build: ./server
    command: sh -c "npm install && npm run dev"
    environment:
      - DATABASE_URL=postgresql://restly:restlypassword@db:5432/restlydb
      - JWT_SECRET=dev_secret_please_change
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  dbdata:
